@echo Building GLFW Application...
g++ -c -I. src/glfw2.cpp
@echo Compilation complete, proceeding to linking...
g++ -o app.exe glfw2.o -L. -lglfw3 -lopengl32 -lgdi32 -lglew32 
@echo Linking complete, running application...
.\app
